// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"database/sql"
)

type Convo struct {
	ID     int64
	Title  sql.NullString
	Slug   sql.NullString
	System sql.NullString
}

type Message struct {
	ID      int64
	Role    string
	Msg     string
	ConvoID sql.NullInt64
}

type Migration struct {
	Name string
}

type Pin struct {
	ID      int64
	ConvoID sql.NullInt64
}

type Setting struct {
	Codify bool
	Model  string
	Editor string
	Temp   float64
}
